const findings=[
 {id:'KYCR-F005',severity:'Critical',title:'Required applicant documents remain unreadable',detail:'The passport PDF preview stays black, the photograph preview stays blank, and the visible Open document fallback produces no navigation. A reviewer cannot defensibly approve identity evidence.',scenarios:'KYCR-004 · KYCR-006 · KYCR-009'},
 {id:'KYCR-F003',severity:'High',title:'Unique queue search returns duplicate applications',detail:'Searching the Pending queue for one exact synthetic applicant renders the identical row three times, breaking queue identity and count reliability.',scenarios:'KYCR-002'},
 {id:'KYCR-F002',severity:'High',title:'Mobile queue actions are off-screen',detail:'At 360×800 and 390×844 the dense reviewer table pushes KYC facts and Review actions beyond the visible viewport without a clear horizontal-scroll affordance.',scenarios:'KYCR-001 · KYCR-002'},
 {id:'KYCR-F001',severity:'High',title:'Stale member state misroutes the employee login',detail:'Opening /kyc-login with an expired member session redirects to the member login. Valid reviewer credentials cannot work there; a second direct navigation is required.',scenarios:'KYCR-001'},
 {id:'KYCR-F004',severity:'Medium',title:'Adjacent period controls expose the wrong accessible name',detail:'Changing Your Progress to 14 or 30 days causes the Request Distribution control to inherit that accessible name while visibly remaining Last 7 days.',scenarios:'KYCR-003'}
];
const names=['Employee authentication and session boundaries','Queue status counts, search and pagination','Assignment overview and dashboard metrics','Submitted facts and individual evidence','Sensitive reveal reasons and audit','Document preview failure and owner isolation','Field decisions, comments and draft persistence','Professional qualifications and optional evidence','Financial identifiers and declarations','Referee response and refresh lifecycle','Email verification resend and proof of control','Concurrent review and stale-record protection','Network interruption and resumable work','Keyboard, screen reader and responsive workbench','First review assignment and start','Submit reviewed individual for approval','Rejected evidence blocks submit','Reject application and applicant resubmission','Approver return and reviewer rework','Current validity and new requirements','Corporate submission to mark reviewed','Corporate reject, correct and resubmit','AIR queue search, filters and evidence','AIR approve and withdrawal release','AIR reject and corrective response','Correction case claim, query and member response','Correction case resolution and release','Appeal lifecycle and independent outcome','Full individual onboarding to investment','Full corporate KYB and compliance closeout'];
const state={1:'fail',2:'fail',3:'progress',4:'progress',5:'progress',6:'fail',8:'progress',9:'progress',10:'blocked'};
const label={fail:'Failure found',progress:'In progress',blocked:'Blocked','not-run':'Not run'};
const findingList=document.querySelector('#finding-list');
const coverageGrid=document.querySelector('#coverage-grid');
function renderFindings(){const value=document.querySelector('#severity').value;findingList.innerHTML=findings.filter(f=>value==='all'||f.severity===value).map(f=>`<article class="finding"><span class="badge ${f.severity}">${f.severity}</span><div><h3>${f.id} · ${f.title}</h3><p>${f.detail}</p></div><code>${f.scenarios}</code></article>`).join('')||'<p>No findings match this filter.</p>'}
function renderCoverage(){const value=document.querySelector('#status').value;coverageGrid.innerHTML=names.map((name,i)=>{const s=state[i+1]||'not-run';return{id:i+1,name,s}}).filter(x=>value==='all'||x.s===value).map(x=>`<article class="scenario"><i class="dot ${x.s}"></i><div><strong>KYCR-${String(x.id).padStart(3,'0')}</strong><span>${x.name}</span><span>${label[x.s]}</span></div></article>`).join('')}
document.querySelector('#severity').addEventListener('change',renderFindings);document.querySelector('#status').addEventListener('change',renderCoverage);renderFindings();renderCoverage();

